{% set name = "fastapi-crudrouter" %}
{% set version = "0.8.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/fastapi-crudrouter-{{ version }}.tar.gz
  sha256: 32704a7aa1d0b23bb6437f717599e9c4c01d8e5a91370a0359837a899a809ceb

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - fastapi

test:
  imports:
    - fastapi_crudrouter
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/awtkns/fastapi-crudrouter
  summary: A dynamic FastAPI router that automatically creates CRUD routes for your models
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - sumanth-manchala
